### ISSUE TITLE
Inter NetApp Relay

### ISSUE THREAD

**Issue by Artonus** [5G-ERA/middleware#181]
The result of the talk with BUT to support the Multi NetApp Relay has concluded that the Middleware will have to develop additional support.

The Middleware will have to deploy a new NetApp for each action in the action plan. The Relay will be given the list of NetApps and Topics to which the topics must be routed. 
On top of this, the switch in the ActionPlan needs to be added to enable the routing through the gateway, only to this new RelayNetApp.

The format of the topics is as below:
```
[
   {
      "relay_address":"IP_OR_HOSTNAME",     
      "topics":[
         "TOPIC_NAME_1",
         "TOPIC_NAME_2",
         "TOPIC_NAME_3"
      ],
      "services": [
      	 "/test_srvs2"
      ]
   },
   {
      "relay_address":"IP_OR_HOSTNAME",      
      "topics":[
         "TOPIC_NAME_1",
         "TOPIC_NAME_2",
         "TOPIC_NAME_3"
      ],
     "services": [
      	 "/test_srvs2"
      ]
   },
   {
      "relay_address":"IP_OR_HOSTNAME",
      "topics":[
         "TOPIC_NAME_1",
         "TOPIC_NAME_2",
         "TOPIC_NAME_3"
      ],
      "services": [
      	 "/test_srvs2"
      ]
   }
]

```

## TODO:

- [x] Add new property indicating that `Action` will be covered by a single Relay traffic
- [x] Mapping of the NetApp topics, addresses and ports to the RelayNetApp configuration
- [x] RelayNetApp definition, including environment variable configuration
- [x] Deployment of the RelayNetApp
- [x] Route the traffic from the Gateway just to RelayNetApp
- [x] Delete the RelayNetApp with the Action Plan (needs ServiceInstanceId)
- [x] Close the Route from Gateway to RelayNetApp

**Comment by Artonus** [comment]
Update:
After agreeing with Michal, we have decided that the `relay_port` field from the config is not needed. I have adjusted the original structure accordingly.
